name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Download dependencies
      run: ./gradlew build --no-daemon

    - name: Build APK
      run: ./gradlew assembleRelease --no-daemon

    - name: Verify APK exists
      run: |
        if [ ! -f app/build/outputs/apk/release/app-release-unsigned.apk ]; then
          echo "APK not found!"
          exit 1
        fi

    - name: Sign APK
      env:
        KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        # Ensure the APK file path is correct
        APK_PATH=app/build/outputs/apk/release/app-release-unsigned.apk
        if [ ! -f "$APK_PATH" ]; then
          echo "APK file not found at $APK_PATH"
          exit 1
        fi
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore "$KEYSTORE_PATH" -storepass "$KEYSTORE_PASSWORD" -keypass "$KEY_PASSWORD" "$APK_PATH" "$KEY_ALIAS"
        $ANDROID_HOME/build-tools/34.0.0/zipalign -v 4 "$APK_PATH" app/build/outputs/apk/release/app-release.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
